### PR TITLE
Switch to govendor

### PR DESCRIPTION
**Pull request by sargun**

### CODE REVIEW

**Comment by jdef** [comment]
any particular reason that you're not bundling in the vendored code? I saw that with rexray builds were much more stable on TC when all the code deps were vendored and committed as part of the code base vs. resolved/downloaded at build time. Also made for faster builds

**Comment by sargun** [comment]
I find it really ugly. It's hard to track down what's going on when someone changes a dep and maybe 1 or 2 lines. Nonetheless, it wouldn't be difficult to add the code back in. You're right about stable builds, but in exchange for unparseable diffs, I do not know.

**Comment by sargun** [comment]
Nonetheless, we can always add deps. I really wouldn't want to add deps in this PR, just for clarity (and sanity) sake.

**Comment by jdef** [comment]
as long as changes to vendor/ code are grouped into a single commit
separate from other changes then diff's are pretty easy to review

**Comment by sargun** [comment]
How about this:
(1) Merge to the vetshadow changes fixed
(2) Merge to vendor
(3) Merge to add deps to repo

As three separate PRs?

**Comment by jdef** [comment]
sounds good to me

**Comment by sargun** [comment]
@jdef Mergeable?

**Comment by jdef** [comment]
lgtm once it passes CI

**Pull request merged**
