### PR TITLE
detect: prefer ip address over hostname

### LINKED ISSUE #289: Prefer IP addresses over hostnames
What version of the project are you using?
https://github.com/mesosphere/mesos-dns/commit/b8922a49e14bbf346f0048ab571f688e1ee47813

What operating system and processor architecture are you using?
OSX/amd64

What did you do?
I started a 1-zookeeper/3-mesos-master/1-mesos-dns testbed as described in https://github.com/mesosphere/mesos-dns/issues/276#issuecomment-143468209.

I issued an A-record query:
`$ dig @127.0.0.1 -p 5253 master.mesos +short A`

What did you expect to see?
I expect to get the complete list of master IPs:
```
127.0.0.2
127.0.0.3
127.0.0.4
```

What did you see instead?
I get only one IP address:
```
127.0.0.2
```

### PR DESCRIPTION
**Pull request by s-urbaniak**
Fixes #289, #276

### CODE REVIEW

**Comment by s-urbaniak** [comment]
@tsenart PTAL

**Comment by tsenart** [comment]
LGTM

**Comment by jdef** [comment]
Probably worth adding a TODO in here to upgrade to MasterInfo.Address as soon as mesos-go makes that available via updated protos. That way you don't need to be in the business of big-vs-little endian decoding (which there were some plans to change at some point).

**Comment by jdef** [comment]
It sounds like little vs. big endian encoding depends on the arch that the remote UPID process is running on: https://issues.apache.org/jira/browse/MESOS-1201

**Comment by jdef** [comment]
The "trivial" fix uses `ntohl` for the ordering problem (copied from the xref'd MESOS issue above):
```
 // you get the minfo from … magic!
  MasterInfo minfo = getMyMasterInfo(...);

  // then convert the bytes into host-order:
  net::IP ip{ ntohl(minfo.ip()) };
  // you can then generate back the original string ("192.168.1.10")
  std::ostringstream out;
  out << ip;
  return out.str();
```

**Comment by s-urbaniak** [comment]
@jdef PTAL (just added a TODO)

**Comment by tsenart** [comment]
@s-urbaniak: TODOs in code get easily lost. Please create an issue to track this instead.

**Comment by s-urbaniak** [comment]
@tsenart you are very right, I just created #291

**Comment by jdef** [comment]
actually wondering if it makes sense to extract this packing logic into a
set of separate go files controlled by build flags to target different
arch's since each may have different endian-ness:
https://golang.org/doc/install/source

**Comment by tsenart** [comment]
@jdef: No need to do that after implementing https://github.com/mesosphere/mesos-dns/issues/291 since it is a string, not an int.

**Comment by jdef** [comment]
lgtm. we're probably not going to make things any worse for people since
it's already broken. there's a (slight) chance that by fixing this for 99%
of people maybe it breaks for 1% of others. this issue, in general, isn't
fully resolvable without upgrading to the v0.24 bindings. which I don't
think mesos-go has generated protos for yet.

**Comment by tsenart** [comment]
Even if we update the bindings, this new address field would only be set in more recent versions of Mesos, so older clusters would still be affected.

**Comment by jdef** [comment]
true, but given the current deprecation cycle systems need to upgrade
quickly to stay compat. @nqn sent something to the mesos-dev list recently
about the fast-pace of the current deprecation process and how it might
make sense to slow it down.

**Comment by jdef** [comment]
like the byte order detection

**Comment by s-urbaniak** [comment]
small nit, otherwise I really like the refactorings, LGTM

**Pull request merged**
