### PR TITLE
Wait for a reload before serving DNS

### PR DESCRIPTION
**Pull request by nlsun**

### CODE REVIEW

**Comment by nlsun** [comment]
@mesosphere-ci retest me please

**Comment by nlsun** [comment]
@mesosphere-ci Retest this please.

**Comment by nlsun** [comment]
@mesosphere-ci Retest this please.

**Comment by nlsun** [comment]
@mesosphere-ci Retest this please.

**Comment by nlsun** [comment]
@mesosphere-ci Retest this please.

**Comment by gpaul** [comment]
Consider using a channel instead of a bool for `ready` in the resolver. Then where you set `ready=true`, `res.readyCh <- true` instead. And change `Ready()` to `WaitUntilReady()`

```
func WaitUntilReady() {
  <-res.readyCh
}
```

This way you don't need the sleep.

If you had several people calling `Ready()` (or `WaitUntilReady()`) you would have to use `close(res.readyCh)` instead of just sending a bool to it. In that case, just be careful because you will need to replace `res.readyCh` with a fresh channel at the top of `Reload()` so you don't get a `close of closed channel` error.

**Comment by nlsun** [comment]
@gpaul Agreed, I've switched to using a channel.

**Comment by nlsun** [comment]
@mesosphere-ci Retest this please.

**Comment by nlsun** [comment]
@mesosphere-ci Retest this please.

**Comment by gpaul** [comment]
Nice one :ship:

**Comment by nlsun** [comment]
@mesosphere-ci Retest this please.

**Pull request merged**
