### PR TITLE
Implement service enumeration

### PR DESCRIPTION
**Pull request by tony-kerz**
per https://github.com/mesosphere/mesos-dns/issues/294

### CODE REVIEW

**Comment by tony-kerz** [comment]
@tsenart this is my first pass. i closed it after i realized that i am returning a list of {service, host, ip, port} which probably isn't what you want, as you specified [PTR](http://help.dnsmadeeasy.com/managed-dns/dns-record-types/ptr-record/) type info v [SRV](http://help.dnsmadeeasy.com/managed-dns/dns-record-types/srv-record/). 

can you provide an example of the json you would expect to see in a response?

best,
tony.

**Comment by tsenart** [comment]
@tony-kerz: This being a DNS server, the primary enumeration mechanism I had in mind was the one described in https://tools.ietf.org/html/rfc6763#section-9. We could start with the HTTP API for such functionality but that feels backwards.

**Comment by tony-kerz** [comment]
i see what you are saying, makes perfect sense in that context. appreciate the insight, thx!

**Comment by jdef** [comment]
Not all client will be able to speak DNS. I'm fine starting out with the
HTTP approach to gauge usefulness of this feature. The whole reason that we
added the HTTP API was because many clients/libraries have difficulty
speaking anything but the most simple aspects of the DNS protocol.

**Comment by tsenart** [comment]
@jdef, @tony-kerz: Is this particular feature, enumeration, targeted at programs or humans? If it is targeted at humans, as I think it is , then documentation of the DNS API ought to be sufficient. Any sysadmin can learn that `$ dig _services._dns-sd._udp.mesos. PTR` will return the available services.

**Comment by tony-kerz** [comment]
in my particular case, i wanted to go after a service, but i wasn't sure what the service-name was, so i was just wishing for a mechanism to show available services. i was logged onto an aws-dcos-slave-node, and i have `curl` at my disposal to hit the mesos-dns-api, but to my knowledge `dig` isn't around by default.

**Comment by jdef** [comment]
Are we really proceeding down the dns-sd path? I forwarded you an internal
email that went around a while back about dns-sd. There were some serious
doubts back then concerning its viability as discovery mechanism for mesos
clusters.

**Comment by jdef** [comment]
That's precisely one of the problems that we were trying to target -- not
all clients have DNS tooling available. Almost all clients can speak HTTP.

**Comment by tsenart** [comment]
Just to be clear, I'm *not* at all against exposing an HTTP endpoint for enumeration as I understand the limitations of available tools in most environments. However, I *do* want that the DNS and HTTP interfaces to have parity.

**Comment by tsenart** [comment]
I'm sorry if that wasn't clear from my first comment.

**Comment by sargun** [comment]
@tony-kerz -
I'd love for you to update your PR, and ideally split it it into two. Your notes about getting started with development are great, but I wish they were in their own PR.

**Comment by sargun** [comment]
Record enumeration seems to fulfill most of these needs

**Pull request closed without merging**
