### PR TITLE
Command Line flags and Evironment Varaiable

### PR DESCRIPTION
**Pull request by jrossi**
This adds support cli args and environment variables. 

Should be easy and discoverable how to work with the features.  I did not attempt to keep backwards compatibility of any of the current cli flags as I figured this was better (I could be wrong).  I also merged (baddly but works) the VeryVerbose stuff.  This is not good to look at, but I will correct that with a pull request to do better logging.  Something that supports levels like debug, info, etc....

Some work will still need to be done as I need to clean up the wording, but I want to put this PR sooner rather then later.  (Suggestions always welcome).  

```
NAME:
   mesos-dns - DNS-based service discovery for Mesos

USAGE:
   mesos-dns [global options] command [command options] [arguments...]

VERSION:
   0.1

AUTHOR:
  Author - <unknown@email>

COMMANDS:
   help, h      Shows a list of commands or help for one command

GLOBAL OPTIONS:
   -V, --verbose                         [$MESOS_DNS_VERBOSE]
   --VV, --veryverbose                   [$MESOS_DNS_VERYVERBOSE]
   -j, --jsonconfig                     json configuration file [$MESOS_DNS_JSONCONFIG]
   -m, --masters "127.0.0.1:5050"       comma sperated list of mesos master servers example: 1.1.1.1:5050,2.2.2.2:5050,3.3.3.3:5050 [$MESOS_DNS_MASTERS]
   -s, --refreshseconds "1s"            The frequency at which Mesos-DNS updates DNS records  [$MESOS_DNS_REFRESH]
   -t, --ttl "1s"                       The time to live value for DNS records served by Mesos-DNS [$MESOS_DNS_TTL]
   -d, --domain "mesos"                 The domain name for the Mesos cluster [$MESOS_DNS_DOMAIN]
   -p, --port "53"                      The port number that Mesos-DNS monitors for incoming DNS requests [$MESOS_DNS_PORT]
   -r, --resolver                       A comma separated list with the IP addresses of external DNS servers that Mesos-DNS will contact to resolve any DNS requests outside the domain. [$MESOS_DNS_RESOLVER]
   -T, --timeout "5s"                   The timeout threshold, requests to external DNS requests. [$MESOS_DNS_TIMEOUT]
   -l, --listener "0.0.0.0"             The IP address of Mesos-DNS. In SOA replies. [$MESOS_DNS_LISTENER]
   -e, --email "root.mesos-dns.mesos"   The email address of the Mesos domain name administrator. In Soa replies. [$MESOS_DNS_EMAIL]
   --help, -h                           show help
   --version, -v                        print the version

```

Started as #97

### CODE REVIEW

**Comment by kozyraki** [comment]
@jrossi thanks. I am working on Zookeeper integration at this point and will get to that later on. Unfortunately, my expectation is that this will require changes to your PR. I will let you know when I get there.

**Comment by jrossi** [comment]
@kozyraki No problem let me know i can keep it up to date no issue.

**Comment by jrossi** [comment]
@kozyraki Could not find the Repo with the zookeeper work was going on.  Is it public?

**Comment by kozyraki** [comment]
it is the zk branch by me. but I would not waste much time on this for now.
it is still in progress.

**Comment by tsenart** [comment]
I'd like us to have a single method to configure mesos-dns, and I'd like that to be flags. Right now things are split across file and flags which isn't very well thought out from a usability standpoint. What would configuration through environment variables provide that flags wouldn't?

**Comment by tsenart** [comment]
Replaced by #257

**Pull request closed without merging**
