### PR TITLE
check if slave IP string contains a valid IP address

### PR DESCRIPTION
**Pull request by lloesche**
This checks if the string returned by sanitizedSlaveAddress() contains a valid IP address.

### CODE REVIEW

**Comment by jdef** [comment]
Thanks for this. I think I'd rather see `sanitizedSlaveAddress` return `(string,bool)` where the bool indicates "valid ip address" (basically just forward `ok`); avoids redundant parsing.

**Comment by lloesche** [comment]
Like so?

**Comment by jdef** [comment]
yep. looks like a unit test fails to build now..

**Comment by tsenart** [comment]
Why is this required?

**Comment by lloesche** [comment]
Right sorry forgot about the tests. Should be fixed.

**Comment by lloesche** [comment]
@tsenart if I understand it correctly there's cases where sanitizedSlaveAddress() will return 
labels.AsDomainFrag() instead of a valid IPv4 address. Which would then create invalid A records.

**Comment by tsenart** [comment]
@lloesche: Then what you want to use is not `sanitizedSlaveAddress` but `address, ok := hostToIP4(hostname)` directly!

**Comment by jdef** [comment]
@tsenart an implication of my suggested approach would preserve the existing behavior of assigning the result of sanitizedSlaveAddress to SlaveIPs, and address the corner case whereby a non-IP-address would be used to construct an A record.

I don't know where else SlaveIPs is used without further code review.

**Comment by lloesche** [comment]
@tsenart but that's what sanitizedSlaveAddress() is doing already. Given a cluster of 10.000 slave nodes I would suddenly do 20k hostname lookups instead of 10k every 5 sec.

**Comment by tsenart** [comment]
@lloesche: I'm not suggesting that :) I'm saying that I'd get rid of the `sanitizedSlaveAddress` and in-line it.

**Comment by lloesche** [comment]
@tsenart but sanitizedSlaveAddress() was already used before I added my slave.mesos code to it.
The original code had an assignment
```
rg.SlaveIPs[slave.ID] = sanitizedSlaveAddress(slave.Hostname, spec)
```
And I just added my slave.mesos code in there. I don't know what rg.SlaveIPs[slave.ID] does or where it's used so can't just get rid of sanitizedSlaveAddress().

**Comment by jdef** [comment]
I vote for keeping this change as is and we can open a new PR to refactor sanitizeSlaveAddress

**Comment by tsenart** [comment]
@lloesche: Sure you can. It isn't used anywhere else.
```go
for _, slave := range sj.Slaves {
    address, ok := hostToIP4(slave.Hostname)
    if ok {
        rg.insertRR("slave."+domain+".", address, "A")
    } else {
        address = labels.AsDomainFrag(address, spec)
    }
    rg.SlaveIPs[slave.ID] = address
}
```

**Comment by lloesche** [comment]
@tsenart ha cool, updated. How would I know that it's not used anywhere outside generator.go? Just grep the entire sources? I'm using vim to edit. Is there an IDE or some other way that would show me all references?

**Comment by tsenart** [comment]
Yes, you can use grep. I personally use [Ag](https://github.com/ggreer/the_silver_searcher).
For smarter Go static analysis tools, install https://github.com/fatih/vim-go
Then you can call `:GoCallers` on your function.

**Comment by tsenart** [comment]
LGTM

**Pull request merged**
