### PR TITLE
WIP: Plugins (v2) API Support

### LINKED ISSUE #62: support for plugins
I'm thinking of how I might bridge kubernetes service discovery and mesos service discovery. Part of a solution might be a mesos-dns "plugin" that watches the kubernetes service registry and manages DNS records for kubernetes services inside mesos-dns (so that mesos tasks using mesos-dns services for resolution can also see kubernetes services). The other half of a solution might be an additional kubernetes service endpoint controller that watches mesos tasks (like mesos-dns does) and manages kubernetes endpoint records (so that kubernetes pods can find mesos services hosted by other frameworks).

Any thoughts re: a plugin model?

### PR DESCRIPTION
**Pull request by jdef**
- supersedes #110 
- fixes #62
- high-level changelog
  - hide master polling implementation behind event (`records/config`) model
    - we still poll master :(
    - plugins don't have to poll, they can push
  - plugins!
    - can register additional HTTP containers
    - can register pre/post processing filters for records generated from mesos tasks
    - can wrap the record generation function for tasks records
    - can register additional record sources
    - HTTP and DNS servers both run as plugins
- TODO
  - [ ] document features, provide examples, add more tests

### CODE REVIEW

**Comment by sttts** [comment]
LGTM as far as I can judge without actually testing it.

**Comment by jdef** [comment]
xref #62

**Comment by F21** [comment]
Any updates on this?

**Comment by jdef** [comment]
@F21 we're in the process of rationalizing the decisions that drove this prototype. we'll probably end up with a v3 that reuses some of these ideas but probably somewhat more narrow in scope -- this is pretty huge PR. did you have any specific feedback to offer with respect to approach that this PR demonstrates?

**Comment by F21** [comment]
@jdef Not specific feedback pertaining to this PR, but I am currently setting up a test mesos cluster with the kubernetes-mesos framework. Kubernetes appears to have a kube-dns add-on for resolving services, so I would love to see how that will get integrated with the mesos-dns project.

In order words, I would love to be able to resolve things like `blah.marathon.mesos` or `namenode1.hdfs.mesos` from within a container in a kubernetes pod as well as resolve things like `my-svc.my-namespace.svc.cluster.local` from outside kubernetes to point to a kubernetes object.

**Comment by jdef** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/125

**Comment by jdef** [comment]
@F21 kubernetes has various options for configuring DNS resolution within pod containers. I think that the default is that pod CT's inherit the node's resolve.conf settings. So if your node's already have a nameserver record that points to mesos-dns your pods should already be able to resolve mesos services.

An ideal mesos-dns/k8s plugin would provide records in mesos-dns, in the .mesos domain, that point to k8s services. There are complicating factors here: for example, k8s service IPs are magical because they're managed by kube-proxy/iptables; only those tasks running on slaves that are *also* running kube-proxy would be able to access those service IPs. Unless we changed how the k8s framework deployed kube-proxy across the cluster (and there are complications there too).

**Comment by jdef** [comment]
FWIW the FrameworkInfo.Labels field is should land in mesos-0.24.0:
- https://issues.apache.org/jira/browse/MESOS-2841

this facilitates mesos-dns discovering mesos-dns-plugin capabilities offered by frameworks.

**Comment by jdef** [comment]
Closing this out since no one seems interested in landing this.

**Pull request closed without merging**
