### PR TITLE
Generate framework A and SRV records

### LINKED ISSUE #202: Resolve schedulers as well as tasks.
I would like to resolve where my scheduler is running. `ping marathon.mesos` should return the IP of the scheduler that is connected to mesos.

### PR DESCRIPTION
**Pull request by tsenart**
Depends on #208 and closes #202.

### CODE REVIEW

**Comment by tsenart** [comment]
PTAL: @sttts, @jdef, @pyronicide

**Comment by tsenart** [comment]
Only the last commit is relevant.

**Comment by sttts** [comment]
One comment, otherwise lgtm

**Comment by sttts** [comment]
Same question as for slave: why udp. Otherwise lgtm

**Comment by tsenart** [comment]
Oh, I see. That's scheduler Mesos port which is TCP only. Cool, I'll drop the UDP.

**Comment by jdef** [comment]
Why did we add an SRV record for schedulers? The PID port is the driver
port, and should only be used by mesos -- what need is there for it to be
discoverable?

**Comment by pyronicide** [comment]
@jdef you could use the webui_url? That's an actual url though, so I'm not sure it works out right.

**Comment by jdef** [comment]
we could probably attempt to parse webui_url for a host:port. if not found,
we could default to the scheduler PID info (this merged PR). how does that
sound?

On Sat, Aug 1, 2015 at 10:56 AM, Thomas Rampelberg <notifications@github.com

**Comment by pyronicide** [comment]
:+1: that sounds perfect.

**Pull request merged**
