### PR TITLE
Rename iam secret to private_key

### PR DESCRIPTION
**Pull request by drewkerrigan**

### CODE REVIEW

**Comment by drewkerrigan** [comment]
@jdef @sargun please review when you have a chance.

**Comment by sargun** [comment]
Gotta update: https://github.com/mesosphere/mesos-dns/blob/master/docs/docs/configuration-parameters.md

Other than that, looks okay

**Comment by drewkerrigan** [comment]
@sargun looks like the example in https://github.com/mesosphere/mesos-dns/blob/master/docs/docs/configuration-parameters.md uses `basic` authentication which is still using "principal" and "secret". The only thing that this PR changes is the `iam` authentication mechanism (which now uses "uid", "private_key", and "login_endpoint").

**Comment by jdef** [comment]
lgtm. please loop in the dcos security team on this if not already because this will impact them

**Pull request merged**
