### PR TITLE
Support multiple listeners

### LINKED ISSUE #87: Be able to bind mesos-dns to multiple interfaces
Right now the "listener" option only takes one IP. It would be good if I could bind mesos-dns to several IPs so that it is available from e.g. the office via the servers public interface as well as on the internal network via it's internal interface. But I don't want it to bind to the VM network or the Docker interface so I can't bind it to 0.0.0.0.

### PR DESCRIPTION
**Pull request by discordianfish**
This changes the listener parameter to listeners list parameter.
mesos-dns will try to bind each address and also use them for the
generated records like the SOA and mesos-dns records.

This closes #87.

### CODE REVIEW

**Comment by kozyraki** [comment]
@discordianfish Thanks a lot, this is very useful!
I may not get to test it this week but I will try to get to it as soon as possible. I think we need a couple more tests in resolver_test.go to be on the safe side too.

**Comment by discordianfish** [comment]
@kozyraki The problem is, testing the multiple listeners requires the test to bind additional IPs to some interface for which there is no platform independent way.

**Comment by BenWhitehead** [comment]
In your tests you might be able to bind to multiple local interfaces `127.0.0.1,127.0.1.1,127.0.2.1` for example and then verify each address responds to requests.

**Comment by discordianfish** [comment]
@BenWhitehead No, you need to configure the IPs to the interface first, at least on linux and osx. On linux you can also set 'net.ipv4.ip_nonlocal_bind=1', but anyway it's a platform specific thing.
So for proper tests, this means either to limit those tests to run only on a some platforms or implement platform specific methods to configure the IPs on all supported platform.

**Comment by BenWhitehead** [comment]
fair enough

**Comment by tsenart** [comment]
@discordianfish: I'm really sorry this got lost on the review queue. We're stepping up our game here! Would you be so kind  as to re-apply your changes to the current master? Thanks.

**Comment by discordianfish** [comment]
Given how simple the change but outdate it is, it probably makes more sense to redo it instead of fixing the merge conflicts.
@lloesche Is this still something we want? If so, I'll do a new PR.

**Pull request closed without merging**
