### PR TITLE
Adds Dockerfile for development

### PR DESCRIPTION
**Pull request by jfarrell**
Add docker build environment to simplify development

### CODE REVIEW

**Comment by tsenart** [comment]
Would you please elaborate on how this simplifies development?

**Comment by jfarrell** [comment]
hey @tsenart, this provides a repeatable development environment which is always the same for dev and ci purposes (travis is in the works of adding docker support as well, currently in beta). If you dont think that this would be used by a broader audience then the pr can be closed

**Comment by tsenart** [comment]
As long as we don't run tests with infrastructure dependencies such as Mesos or Zookeeper, using Dockery is overkill. We already achieve repeatable code builds with dependency vendoring (Godeps).

**Comment by jfarrell** [comment]
The Dockerfile does not add the source or any of its vendored dependencies listed in GoDeps, its intent is to provide a build and test environment that is always the same, so that someone developing locally or using travis/jenkins/circle can have the same base go env setup across the board. Since this does not seem to be a need i'll go ahead and close out the pr

**Pull request closed without merging**
