### PR TITLE
fix: add WaitGroup to accurately measure elapsed time of benchmark

### PR DESCRIPTION
**Pull request by jaredfolkins**
Howdy!

I took a look through this repository and found a small error. I figured in the spirit of saying "hello 👋" I'd ship a fix. 

Thanks,
Jared

    What version of the project are you using?

Master repo - dcos 1.12

    What operating system and processor architecture are you using?

Debian/Linux

    What did you do?

Tried to test a benchmark

    What did you expect to see?

The tool is asserting that it is benchmarking queries.

    What did you see instead?

The tool simply iterates a for loop issuing 10k goroutines, which promptly close. The test isn't performing as desired.

### CODE REVIEW

**Comment by jaredfolkins** [comment]
Sample application.

```go
package main

 

import (

        "log"

        "sync"

        "time"

)

 

func main() {

 

        wg := &sync.WaitGroup{}

 

        start := time.Now()

        cnt := 10000

        for i := 0; i < cnt; i++ {

                sleepy(5, wg)

        }

 

        wg.Wait()

        elapsed := time.Since(start)

        log.Printf("benching took %s", elapsed)

        log.Printf("doing %d/%v rps", cnt, elapsed)

}

 

 

func sleepy(t int, wg *sync.WaitGroup) {

        wg.Add(1)

        go func() {

                time.Sleep(time.Duration(t) * time.Second)

                wg.Done()

        }()

}
```

**Comment by jdef** [comment]
test this please

**Comment by jdef** [comment]
retest this please

**Comment by jdef** [comment]
retest this please

**Comment by jaredfolkins** [comment]
I'm assuming this is all CI related? Were you needing me to do something?

**Comment by jdef** [comment]
Was trying to bump CI. Looks like a bigger CI change is needed. No input
from you needed for now. Thanks.

**Comment by jdef** [comment]
@jaredfolkins would you mind rebasing, in order to exercise our updated CI tooling?

**Comment by jaredfolkins** [comment]
I'm on a deadline today but I'll loop back around to this by Tuesday of
next week. Jf

**Comment by jaredfolkins** [comment]
Whoops. Was doing too many things at once. Let me clean this up.

**Comment by jaredfolkins** [comment]
Alright, that should have cleaned up the history. Let me know.

**Comment by jaredfolkins** [comment]
Hey, just curious your team's procedure for tickling the CI. Is it simply `git commit --amend` as that would change the SHA-1 hash? Maybe there is a better way and I always am learning.

**Comment by jdef** [comment]
That will do it. Public PRs also require approval from an owner before CI
will build them.

**Pull request merged**
