### PR TITLE
Make names and queries case-insensitive

### LINKED ISSUE #84: Query handling should be case-insensitive
The DNS protocol is supposed to be case-insensitive, but it appears that mesos-dns is not.  e.g. a query for mesos-dns.mesos. will work with the included sample config, but Mesos-Dns.mesos. will not. Makes it extra fidgety when frameworks register with mixed-case names...

### PR DESCRIPTION
**Pull request by benley**
This could be done more elegantly, but at least it seems to work for now.  Still needs tests.

Fixes #84

[Review on Reviewable](https://reviewable.io/reviews/mesosphere/mesos-dns/85)

### CODE REVIEW

**Comment by kozyraki** [comment]
@benley Great catch Ben. I am surprised none of us noticed this before. Let me test your branch a little first and then will move forward. Thanks

**Comment by benley** [comment]
Thanks. I'll try to add some unit tests this afternoon if you want to use this patch.

**Comment by kozyraki** [comment]
@benley Great, ping me when the unit tests are in and I will do my side quickly after that. Thanks a lot.

**Comment by benley** [comment]
OK, added some test coverage. Just fyi, this is literally the first time I've edited Go code so look out for noob mistakes :)

**Comment by kozyraki** [comment]
@benley Thanks. I will test it now.

**Comment by kozyraki** [comment]
@benley made a new branch with a few corrections. Will make a pull request from that. 
Thanks

**Pull request closed without merging**
